web: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 60
release: python manage.py migrate --no-input && python create_test_profiles.py && python manage.py collectstatic --no-input
