web: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 60
release: python manage.py migrate --no-input && python manage.py seed_users && python manage.py seed_localities && python manage.py seed_products && python manage.py backfill_targets && python manage.py collectstatic --no-input
