# Generated by Django 6.0.6 on 2026-07-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visimed", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitrecord",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
