# Generated by Django 6.0.6 on 2026-07-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visimed", "0002_email_blank"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telephone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
