# Generated by Django 6.0.6 on 2026-07-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visimed", "0003_user_telephone"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitrecord",
            name="gco_status",
            field=models.CharField(
                choices=[
                    ("Pas intéressé(e)", "Pas intéressé(e)"),
                    ("Intéressé(e)", "Intéressé(e)"),
                    ("Formé(e)", "Formé(e)"),
                    ("Compte GCO créé", "Compte GCO créé"),
                    ("Compte non actif", "Compte non actif"),
                    ("Compte actif", "Compte actif"),
                ],
                default="Pas intéressé(e)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="visitrecord",
            name="qty_meters",
            field=models.IntegerField(default=0),
        ),
    ]
