# Generated by Django 6.0.6 on 2026-08-30 09:54

import django.db.models.deletion
import visimed.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visimed", "0004_visitrecord_gco_status_visitrecord_qty_meters"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("category", models.CharField(blank=True, default="", max_length=60)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "vm_products",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Territory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "wilayas",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of wilaya names covered.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "territories",
                "db_table": "vm_territories",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="visitrecord",
            options={"ordering": ["-date", "-created_at"]},
        ),
        migrations.AddField(
            model_name="visitrecord",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="visitrecord",
            name="next_action",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="visitrecord",
            name="next_action_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="visitrecord",
            name="objections",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="user",
            name="assigned_regions",
            field=models.TextField(
                blank=True, help_text="Legacy free-text regions, kept for display only."
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("med_rep", "Medical Representative"),
                    ("pharma_rep", "Pharmaceutical Representative"),
                ],
                default="med_rep",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="visitrecord",
            name="comment",
            field=models.TextField(blank=True, help_text="Remarques", null=True),
        ),
        migrations.AlterField(
            model_name="visitrecord",
            name="id",
            field=models.CharField(
                default=visimed.models._new_visit_id,
                editable=False,
                max_length=50,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=150)),
                (
                    "normalized_name",
                    models.CharField(db_index=True, default="", max_length=150),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "M"), ("F", "F")],
                        default="",
                        max_length=1,
                    ),
                ),
                ("specialty", models.CharField(blank=True, default="", max_length=80)),
                (
                    "structure_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "potential",
                    models.CharField(
                        choices=[
                            ("KOL", "Key Opinion Leader"),
                            ("A", "High Potential"),
                            ("B", "Medium Potential"),
                            ("C", "Low Potential"),
                        ],
                        db_index=True,
                        default="C",
                        max_length=5,
                    ),
                ),
                (
                    "gco_status",
                    models.CharField(
                        choices=[
                            ("Pas intéressé(e)", "Pas intéressé(e)"),
                            ("Intéressé(e)", "Intéressé(e)"),
                            ("Formé(e)", "Formé(e)"),
                            ("Compte GCO créé", "Compte GCO créé"),
                            ("Compte non actif", "Compte non actif"),
                            ("Compte actif", "Compte actif"),
                        ],
                        default="Pas intéressé(e)",
                        max_length=50,
                    ),
                ),
                ("address", models.TextField(blank=True, default="")),
                (
                    "wilaya",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                ("commune", models.CharField(blank=True, default="", max_length=100)),
                ("telephone", models.CharField(blank=True, default="", max_length=30)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doctors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "vm_doctors",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="visitrecord",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visits",
                to="visimed.doctor",
            ),
        ),
        migrations.CreateModel(
            name="Objective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[("weekly", "Hebdomadaire"), ("monthly", "Mensuel")],
                        default="weekly",
                        max_length=10,
                    ),
                ),
                (
                    "period_start",
                    models.DateField(help_text="First day of the target period."),
                ),
                ("visits_target", models.IntegerField(default=0)),
                ("new_doctors_target", models.IntegerField(default=0)),
                ("orders_target", models.IntegerField(default=0)),
                ("coverage_target_pct", models.IntegerField(default=0)),
                (
                    "rep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objectives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "vm_objectives",
                "ordering": ["-period_start"],
            },
        ),
        migrations.CreateModel(
            name="Pharmacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=150)),
                (
                    "normalized_name",
                    models.CharField(db_index=True, default="", max_length=150),
                ),
                (
                    "structure_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "potential",
                    models.CharField(
                        choices=[
                            ("KOL", "Key Opinion Leader"),
                            ("A", "High Potential"),
                            ("B", "Medium Potential"),
                            ("C", "Low Potential"),
                        ],
                        db_index=True,
                        default="C",
                        max_length=5,
                    ),
                ),
                ("address", models.TextField(blank=True, default="")),
                (
                    "wilaya",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                ("commune", models.CharField(blank=True, default="", max_length=100)),
                ("telephone", models.CharField(blank=True, default="", max_length=30)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "pharmacies",
                "db_table": "vm_pharmacies",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="visitrecord",
            name="pharmacy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visits",
                to="visimed.pharmacy",
            ),
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("confirmed", "Confirmée"),
                            ("delivered", "Livrée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="visimed.doctor",
                    ),
                ),
                (
                    "pharmacy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="visimed.pharmacy",
                    ),
                ),
                (
                    "rep",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions",
                        to="visimed.visitrecord",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="visimed.product",
                    ),
                ),
            ],
            options={
                "db_table": "vm_prescriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="territory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reps",
                to="visimed.territory",
            ),
        ),
        migrations.CreateModel(
            name="VisitProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("samples_qty", models.IntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visimed.product",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presented_products",
                        to="visimed.visitrecord",
                    ),
                ),
            ],
            options={
                "db_table": "vm_visit_products",
            },
        ),
        migrations.AddConstraint(
            model_name="doctor",
            constraint=models.UniqueConstraint(
                fields=("normalized_name", "wilaya"), name="uniq_doctor_name_wilaya"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="objective",
            unique_together={("rep", "period_type", "period_start")},
        ),
        migrations.AddConstraint(
            model_name="pharmacy",
            constraint=models.UniqueConstraint(
                fields=("normalized_name", "wilaya"), name="uniq_pharmacy_name_wilaya"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="visitproduct",
            unique_together={("visit", "product")},
        ),
    ]
